### ISSUE TITLE
Virtualization not enabled for Windows 10 Guest

### ISSUE THREAD

**Issue by glockmane** [M2Team/NanaBox#17]
Build 19044.4412 on both Host and Guest, newest NanaBox Release. Virtualization is not present in the guest:

When adding:

`"ExposeVirtualizationExtensions": true`

to the config, I get Error 0x80004005 when trying to start the VM..

Processor is AMD Ryzen Z1 Extreme and VT is present on the Host..

**Comment by MouriNaruto** [comment]
You need Windows Server 2022 or Windows 11 or later Host OS for nested virtualization on AMD processors.

For more information, please read https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/enable-nested-virtualization#amd-epyc--ryzen-processor-or-later.

Kenji Mouri

**Comment by glockmane** [comment]
Damn, shame on Microsoft.. Read that some Insider Build include this functionality but as I'm using Windows 10 IOT Enterprise LTSC I'm trapped.. But this is not your fault, so not an issue on your side.. Thanks for the quick answer!

**Comment by tang-yikai** [comment]
Same problem here, Host and guest are both Win11 LTSC. CPU model Intel Xeon E5-2697A V4.
I can enable nested virtualization in libvirt/kvm with following configuration:
```xml
  <cpu mode='host-passthrough' check='none' migratable='on'>
    <feature policy='disable' name='hypervisor'/>
  </cpu>
```
However in nanabox, when I set `"ExposeVirtualizationExtensions": true`, what I got in guest OS is that `VirtualMachine: yes` instead of `virtualization: enabled`
